// import "./scss/test.css";
import "./scss/style.scss";
import "./test";
import { pers1 } from "./moduleTest";
import "./app/app.js";
// import "./formulaire";
// console.log("bonjour les amis du zero");
// const exp = 2e2;
// console.log(exp);
// console.log(2 ** 2);
// const a = "12";
// const result = parseInt(a, 10);
// console.log(result);
// const min = 1;
// const max = 10;
// console.log(Math.round(Math.random() * (max - min) + min));
// console.log('bonjour "lune"');
// const fatigue = true;
// const action = "dormir";
// const etatDeFatigue = `jean est${
//   fatigue ? ` fatigué il a besoin de ${action}` : "super en forme"
// }`;
// console.log(etatDeFatigue);
// const text = "je suis le soleil de midi";
// const b = text.endsWith("midi");
// const b1 = text.startsWith("je suis");
// const b2 = text.slice(0, -1);
// const b3 = text.slice(0);
// const b4 = text.slice(-2, -1);
// console.log("silce(2): ", text.slice(2));
// console.log(b);
// console.log(b1);
// console.log("slice(0,-1): ", b2);
// console.log(b3);
// console.log(b4);
// //split
// const x = "terre,soleil,eau";
// const x1 = x.split(",");
// const x2 = x.replace("eau", "liquide");
// console.log(x1);
// console.log(x2);
// console.log(text.search("je"));
// const numberPhone = "0652746740";
// const lastNumber = numberPhone.slice(-4);
// const maskNumber = lastNumber.padStart(numberPhone.length, "*");
// console.log(maskNumber);
// console.log("taille de maskNumber: ", maskNumber.length);
// const email = "biackgeorrdel@gmail.com";
// const lastEmail = email.slice(0, 4);
// const maskEmail = lastEmail.padEnd(email.length, "*");
// console.log(maskEmail);
// const regex = /^[a-z]+/;
// const regex1 = /@[a-z]+\.[a-z]+/;
// console.log(email.match(regex));
// const nameEmail = email.match(regex);
// console.log(nameEmail[0].length);
// const nameEmailSlice = nameEmail[0].slice(0, 4);
// const nameEmailPadEnd = nameEmailSlice.padEnd(nameEmail[0].length, "*");
// const nameEmailMask = email.replace(regex, nameEmailPadEnd);

// console.log(regex1.exec(email));
// const firstEmail = regex.exec(email);
// console.log(nameEmailMask);
// function test() {
//   console.log("Bonjour je suis une fonction");
// }
// const ch1 = "bonjour les 100 les amis du zeros qsd450 rue du nord de fg125";
// console.log(ch1.match(/[a-z]+$/));
// console.log(ch1.match(/[a-z]*\d+/g));
// const regexEmail = /^[a-z]+[-| ]{0,1}\w+@[a-z]+\.[a-z]+$/;
// console.log("jean125@gmal.com".match(regexEmail));
pers1.bonjour();
